[project]
name = "05-data-encryption"
version = "0.1.0"
description = "Secure multi-user data encryption system"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "cryptography>=44.0.2",
    "streamlit>=1.25.0"
]
